[build-system]
requires = ["flit_core >=3.2,<4","myst_parser"]
build-backend = "flit_core.buildapi"

[project]
name = "pyETRC"
authors = [{name = "xep", email = "mxy0268@qq.com"}]
dynamic = ["version", "description"]
